(* ::Package:: *)

(* ::Input:: *)
(**)
(**)
(**)
(*(*BLACK SCHOLES COLLOCATION - 6 NODE TRIANGLES*)*)
(**)
(*TriElements = Import["C:\Documents and Settings\\jlintern\\Desktop\\JLTriElemR3.Dat"];*)
(*TriNodes= Import["C:\Documents and Settings\\jlintern\\Desktop\\JLTriNodesR3.Dat"];*)
(**)
(**)
(*lList={}*)
(*j=1;*)
(*While[j<=Length[TriElements],*)
(*Subscript[l, j]={{TriNodes[[TriElements[[j]][[1]]]][[2]],TriNodes[[TriElements[[j]][[1]]]][[3]]},{TriNodes[[TriElements[[j]][[2]]]][[2]],TriNodes[[TriElements[[j]][[2]]]][[3]]},{TriNodes[[TriElements[[j]][[3]]]][[2]],TriNodes[[TriElements[[j]][[3]]]][[3]]},{TriNodes[[TriElements[[j]][[4]]]][[2]],TriNodes[[TriElements[[j]][[4]]]][[3]]},*)
(*{TriNodes[[TriElements[[j]][[5]]]][[2]],TriNodes[[TriElements[[j]][[5]]]][[3]]},{TriNodes[[TriElements[[j]][[6]]]][[2]],TriNodes[[TriElements[[j]][[6]]]][[3]]},{TriNodes[[TriElements[[j]][[1]]]][[2]],TriNodes[[TriElements[[j]][[1]]]][[3]]}};*)
(*AppendTo[lList,Subscript[l, j]];*)
(*j++;*)
(**)
(*]*)
(*Graphics[Line[lList]]*)
(**)
(**)


(* ::Input:: *)
(**)


(* ::Input:: *)
(*(*Creat Local Reference Triangle*)*)
(*RefTriangle={{0,0},{.5,0},{1,0},{.5,.5},{0,1},{0,.5}};*)
(*f[x_,y_]={1,x,y,x*y,x^2,y^2};*)
(*(*Create Vandermonde Matrix*)*)
(*VandermondeMat={};*)
(*i=1;*)
(*While[i<=Length[RefTriangle],*)
(*AppendTo[VandermondeMat,f[RefTriangle[[i]][[1]],RefTriangle[[i]][[2]]]]*)
(*i++;*)
(*]*)
(*Print[MatrixForm[VandermondeMat]]*)
(*Print["Vandermonde Matrix"]*)


(* ::Print:: *)
(*"Vandermonde Matrix"*)


(* ::Print:: *)
(*\!\( *)
(*TagBox[*)
(*RowBox[{"(", "", GridBox[{*)
(*{"1", "0", "0", "0", "0", "0"},*)
(*{"1", "0.5`", "0", "0.`", "0.25`", "0"},*)
(*{"1", "1", "0", "0", "1", "0"},*)
(*{"1", "0.5`", "0.5`", "0.25`", "0.25`", "0.25`"},*)
(*{"1", "0", "1", "0", "0", "1"},*)
(*{"1", "0", "0.5`", "0.`", "0", "0.25`"}*)
(*},*)
(*GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},*)
(*GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.7]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}], "", ")"}],*)
(*Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\)*)


(* ::Input:: *)
(*(*Inverse Vandermonde - each column contains coefficients for Lagrange polynomial*)*)
(*VandermondeInv=Inverse[VandermondeMat];*)
(*(*Reference Element Polynomials*)*)
(*p[x_,y_]=f[x,y].VandermondeInv;*)
(*Print["Polynomial Matrix"]*)
(*p[x,y]//MatrixForm*)


(* ::Input:: *)
(**)
(*a=\[Gamma]-\[Alpha];*)
(*b=\[Delta]-\[Beta];*)
(*c=\[Sigma]-\[Alpha];*)
(*d=\[Tau]-\[Beta];*)
(*A=({*)
(* {a, c},*)
(* {b, d}*)
(*});*)
(*InvA= Inverse[A];*)
(**)
(*(*Function for sending Element to the Reference*)*)
(**)
(*xyvar[\[Alpha]_,\[Beta]_,\[Gamma]_,\[Delta]_,\[Sigma]_,\[Tau]_,x_,y_]=(InvA).{x,y}-(InvA).{\[Alpha],\[Beta]};*)
(*xvar[\[Alpha]_,\[Beta]_,\[Gamma]_,\[Delta]_,\[Sigma]_,\[Tau]_,x_,y_]=xyvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y][[1]];*)
(*yvar[\[Alpha]_,\[Beta]_,\[Gamma]_,\[Delta]_,\[Sigma]_,\[Tau]_,x_,y_]=xyvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y][[2]];*)
(**)
(**)
(*(*Reference to Element*)*)
(*xyinvvar[\[Alpha]_,\[Beta]_,\[Gamma]_,\[Delta]_,\[Sigma]_,\[Tau]_,x_,y_]=A.{x,y} +{\[Alpha],\[Beta]};*)
(*xinvvar[\[Alpha]_,\[Beta]_,\[Gamma]_,\[Delta]_,\[Sigma]_,\[Tau]_,x_,y_]=xyinvvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y][[1]];*)
(*yinvvar[\[Alpha]_,\[Beta]_,\[Gamma]_,\[Delta]_,\[Sigma]_,\[Tau]_,x_,y_]=xyinvvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y][[2]];*)
(**)
(**)
(*Print["Variable Change transformation for x"];*)
(*xvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y]*)
(*Print["Variable Change transformation for y"];*)
(*yvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y]*)
(**)
(*Print["Inverse Variable Change for x"];*)
(*xinvvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y]//MatrixForm*)
(*Print["Inverse Variable Change for y"];*)
(*yinvvar[\[Alpha],\[Beta],\[Gamma],\[Delta],\[Sigma],\[Tau],x,y]//MatrixForm*)
(**)
(**)
(**)


(* ::Text:: *)
(**)
(**)
(**)
(*x & y: underlying assets (spatial variables), V~ the price of the option contract and  k~ strike price.  T~ time of contract expiration. *)
(* st. dev.sima (volatilty), r~loan rate  *)
(**)
(**)
(*Black Scholes Eqn ( 2 Spatial Variables) *)
(*\[PartialD]V/\[PartialD]t= 1/2 (Subscript[\[Sigma], 1]x)^2 \[PartialD]^2V/\[PartialD]x^2+1/2 (Subscript[\[Sigma], 2]y)^2 \[PartialD]^2V/\[PartialD]y^2+ Subscript[\[Sigma], 1] Subscript[\[Sigma], 2]\[Rho]xy \[PartialD]^2V/(\[PartialD]x\[PartialD]y)+rx \[PartialD]V/\[PartialD]x+ry \[PartialD]V/\[PartialD]y-rV       (x,y,t \[Element] (0,\[Infinity])) x (0,T]*)
(**)
(**)
(*Expanding*)
(**)
(*where V=Subscript[\[CapitalSigma], e] Subscript[\[CapitalSigma], i] Subscript[a, e,i] Subscript[\[Phi], e,i]*)
(**)
(*(\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k + 1\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] \[CapitalEAcute]/(x, y)\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]/-\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] \[CapitalEAcute]/(x, y)\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]/)/\[CapitalDelta]t= \[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/1\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+ \[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/1\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Rho]x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x \[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/rx\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/ry\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/-\[CapitalAAcute]/\[CapitalEAcute]/\[CapitalEGrave]/*)
(*StyleBox[*)
(*SubscriptBox["\[Sum]", "e"], "Input"]\[CapitalEAcute]/\[CapitalEGrave]/*)
(*StyleBox[*)
(*SubscriptBox["\[Sum]", "i"], "Input"]\[CapitalEGrave]/*)
(*StyleBox["r", "Input"] \[CapitalEAcute]/\[CapitalEGrave]/*)
(*StyleBox["(", "Input"]\[CapitalEGrave]/*)
(*StyleBox[*)
(*SubscriptBox["\[Phi]", *)
(*RowBox[{"e", ",", "i"}]], "Input"] \[CapitalEAcute]/\[CapitalEGrave]/*)
(*StyleBox["(", "Input"]\[CapitalEGrave]/*)
(*SubscriptBox[*)
(*StyleBox["x", "Input"], "i"]\[CapitalEGrave]/*)
(*StyleBox[",", "Input"]\[CapitalEGrave]/*)
(*SubscriptBox[*)
(*StyleBox["y", "Input"], "i"]\[CapitalEGrave]/*)
(*StyleBox[")", "Input"]\[CapitalAGrave]/\[CapitalEGrave]/*)
(*StyleBox[")", "Input"]\[CapitalAGrave]/ \[CapitalEGrave]/*)
(*StyleBox[*)
(*SubscriptBox["a", *)
(*RowBox[{"e", ",", "i"}]], "Input"] \[CapitalEGrave]/*)
(*StyleBox[*)
(*RowBox[{"(", *)
(*SubscriptBox["t", "k"], ")"}], "Input"]\[CapitalAGrave]/\[CapitalAGrave]/*)
(**)
(**)
(**)
(*At "j"collocation points*)
(**)
(*\[CapitalAAcute]/\[CapitalEAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]ae\[CapitalAGrave]/\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\[CapitalEAcute]/\[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k + 1\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/] - *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\[CapitalEGrave]/*)
(*SubscriptBox["a", *)
(*RowBox[{"e", ",", *)
(*StyleBox["i",*)
(*FontSlant->"Italic"]}]] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]//\[CapitalDelta]t =\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] \[CapitalEGrave]/*)
(*SuperscriptBox[*)
(*RowBox[{*)
(*StyleBox["(", "Input"], *)
(*RowBox[{*)
(*SubscriptBox["\[Sigma]", "1"], *)
(*SubscriptBox["x", *)
(*RowBox[{*)
(*RowBox[{"e", "'"}], "j"}]]}], ")"}], "2"] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+ \[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/])\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/1\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Rho]x\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x \[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/rx\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/ry\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/-\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]r \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/])\[CapitalAGrave]/)\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]/     *)
(**)
(*(substitute Kronecker Delta for Subscript[\[Phi], e,i(\[CapitalAAcute]/\[CapitalEAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/]\[CapitalAGrave]/)]:)*)
(**)
(*(\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k + 1\[CapitalAGrave]/])\[CapitalAGrave]/ \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Delta]\[CapitalAGrave]/, \[CapitalEAcute]/e', e\[CapitalAGrave]/])\[CapitalAGrave]/ \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Delta]\[CapitalAGrave]/, \[CapitalEAcute]/i, j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]/-\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Delta]\[CapitalAGrave]/, \[CapitalEAcute]/e', e\[CapitalAGrave]/])\[CapitalAGrave]/ \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Delta]\[CapitalAGrave]/, \[CapitalEAcute]/i, j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]/)/\[CapitalDelta]t=\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] \[CapitalEGrave]/*)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*SubscriptBox["\[Sigma]", "1"], *)
(*StyleBox[*)
(*SubscriptBox["x", *)
(*RowBox[{*)
(*RowBox[{"e", "'"}], ",", "j"}]], "Input"]}], ")"}], "2"] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] \[CapitalEGrave]/*)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*SubscriptBox["\[Sigma]", "2"], *)
(*SubscriptBox[*)
(*SubscriptBox[*)
(*StyleBox["y", "Input"], *)
(*RowBox[{"e", "'"}]], "j"]}], ")"}], "2"] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/1\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Rho]x\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x \[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/*)
(*+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[*)
(*SubscriptBox[\[CapitalEAcute]/rx\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/], \[CapitalEAcute]/j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/ry\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\[CapitalEGrave]/*)
(*SubscriptBox[*)
(*StyleBox[*)
(*RowBox[{"r", *)
(*StyleBox["a", "Input"]}]], *)
(*RowBox[{"e", ",", "i"}]] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/\ \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Delta]\[CapitalAGrave]/, \[CapitalEAcute]/e', e\[CapitalAGrave]/])\[CapitalAGrave]/ \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Delta]\[CapitalAGrave]/, \[CapitalEAcute]/i, j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]/   *)
(**)
(**)
(*(for e=e', (Subscript[\[Delta], i,j ]=0  off home element, and = 1 on home element) \[Phi]  has support in local element)*)
(*(and simplifying)*)
(**)
(*\[CapitalAAcute]/\[CapitalEAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k + 1\[CapitalAGrave]/])\[CapitalAGrave]/ - *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[CapitalDelta]t\[CapitalAGrave]/] = *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] \[CapitalEGrave]/*)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*SubscriptBox["\[Sigma]", "1"], *)
(*StyleBox[*)
(*SubscriptBox["x", *)
(*RowBox[{*)
(*RowBox[{"e", "'"}], ",", "j"}]], "Input"]}], ")"}], "2"] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/] + *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] \[CapitalEGrave]/*)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{*)
(*SubscriptBox["\[Sigma]", "2"], *)
(*StyleBox[*)
(*SubscriptBox["y", *)
(*RowBox[{"e", "'"}]], "Input"]}], *)
(*StyleBox[*)
(*SubscriptBox[",", "j"], "Input"]}], ")"}], "2"] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]'\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/] + *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/1\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Rho]x\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x \[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/*)
(*+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/rx\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/ry\[CapitalAGrave]/, \[CapitalEAcute]/e' j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/a\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/t\[CapitalAGrave]/, \[CapitalEAcute]/k\[CapitalAGrave]/])\[CapitalAGrave]/ *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e', i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/e', j\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/e'\[CapitalAGrave]/]\[CapitalAGrave]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/,\[CapitalAGrave]/, \[CapitalEAcute]/j\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+Subscript[ra, e',j](Subscript[t, k]) *)
(**)
(**)
(**)
(**)
(*Vectors and Matrices*)
(**)
(**)
(**)
(*({*)
(* {(\[PartialD]Subscript[a, 0](t))/(\[PartialD]t*)
(*  ...)},*)
(* {(\[PartialD]Subscript[a, n-1](t))/\[PartialD]t}*)
(*})=K({*)
(* {Subscript[a, 0](t)*)
(*  ...},*)
(* {Subscript[a, n-1](t)}*)
(*})  *)
(* *)
(*and*)
(**)
(*(  {*)
(* {Subscript[a, 0](Subscript[t, m+1])*)
(*  ...},*)
(* {Subscript[a, n-1](Subscript[t, m+1])}*)
(*})=(\[CapitalDelta]tK+I)({*)
(* {Subscript[a, 0](Subscript[t, m])*)
(*  ...},*)
(* {Subscript[a, n-1](Subscript[t, m])}*)
(*})*)
(**)
(*Where*)
(*K= (    \[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/1\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+ \[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/1\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]\ *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/1\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sigma]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Rho]x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SuperscriptBox[\[CapitalEAcute]/\[PartialD]\[CapitalAGrave]/, \[CapitalEAcute]/2\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x \[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/rx\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]x\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/+\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/ry\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/] *)
(*\[CapitalEGrave]/FractionBox[\[CapitalEAcute]/\[PartialD]*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/x\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/], *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/y\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/])\[CapitalAGrave]/\[CapitalAGrave]/, \[CapitalEAcute]/\[PartialD]y\[CapitalAGrave]/]\[CapitalAGrave]/\[CapitalAGrave]/-\[CapitalAAcute]/\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/e\[CapitalAGrave]/]\[CapitalEAcute]/*)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Sum]\[CapitalAGrave]/, \[CapitalEAcute]/i\[CapitalAGrave]/]r \[CapitalEAcute]/( *)
(*\[CapitalEGrave]/SubscriptBox[\[CapitalEAcute]/\[Phi]\[CapitalAGrave]/, \[CapitalEAcute]/e, i\[CapitalAGrave]/] \[CapitalEAcute]/(\[CapitalEGrave]/*)
(*SubscriptBox[*)
(*StyleBox["x", "Input"], "i"]\[CapitalEGrave]/*)
(*StyleBox[",", "Input"]\[CapitalEGrave]/*)
(*SubscriptBox[*)
(*StyleBox["y", "Input"], "i"])\[CapitalAGrave]/)\[CapitalAGrave]/\[CapitalAGrave]/\[CapitalAGrave]/)*)
(**)
(**)
(*We will solve for the A matrix, by utilizing  FDM *)
(**)
(**)
(**)
(**)
(**)


(* ::Input:: *)
(*(*As follows, we will loop through the elements, and evaluate BS function at*)
(*the nodes of each element*)*)
(*(*x & y: underlying assets spatial variables, V~ the price of the option contract,*)
(* st. dev.sima (volatilty), \[Rho]=correlation between assets, r~loan rate  *)*)
(*Subscript[\[Sigma], 1]=.2;*)
(*Subscript[\[Sigma], 2]=.25;*)
(*r=.1;*)
(*\[Rho]=.2;*)
(*globalM=SparseArray[{Band[{1,1}]  ->1},{Length[TriNodes],Length[TriNodes]}];*)
(*globalK=ConstantArray[0,{Length[TriNodes],Length[TriNodes]}];*)
(*globalKM=ConstantArray[0,{Length[TriNodes],Length[TriNodes]}];*)
(**)
(*elem=1;*)
(*While[elem<=Length[TriElements],*)
(*\[Alpha]val=TriNodes[[TriElements[[elem]][[1]]]][[2]];*)
(*\[Beta]val=TriNodes[[TriElements[[elem]][[1]]]][[3]];*)
(*\[Gamma]val=TriNodes[[TriElements[[elem]][[3]]]][[2]];*)
(*\[Delta]val=TriNodes[[TriElements[[elem]][[3]]]][[3]];*)
(*\[Sigma]val=TriNodes[[TriElements[[elem]][[5]]]][[2]];*)
(*\[Tau]val=TriNodes[[TriElements[[elem]][[5]]]][[3]];*)
(**)
(*xaffine[\[Koppa]_,\[Stigma]_]=xyvar[\[Alpha]val,\[Beta]val,\[Gamma]val,\[Delta]val,\[Sigma]val,\[Tau]val,x,y][[1]];*)
(*yaffine[\[Koppa]_,\[Stigma]_]=xyvar[\[Alpha]val,\[Beta]val,\[Gamma]val,\[Delta]val,\[Sigma]val,\[Tau]val,x,y][[2]];*)
(**)
(**)
(*\[Phi][x_,y_]=p[xaffine[x,y],yaffine[x,y]];*)
(*dx\[Phi][x_,y_]=D[\[Phi][x,y],x];*)
(*dy\[Phi][x_,y_]=D[\[Phi][x,y],y];*)
(*ddx\[Phi][x_,y_]=D[dx\[Phi][x,y],x];*)
(*ddx\[Phi]new[x_,y_]=D[\[Phi][x,y],{x,2}];*)
(*ddy\[Phi][x_,y_]=D[dy\[Phi][x,y],y];*)
(*dxdy\[Phi][x_,y_]=D[dx\[Phi][x,y],y];*)
(**)
(*(*Local K Matrices*)*)
(*localK=ConstantArray[0,{6,6}];*)
(**)
(*ii=1;*)
(*While[ii<=6,*)
(*jj=1;*)
(*While[jj<=6,*)
(*\[CapitalPsi]=TriNodes[[TriElements[[elem]][[ii]]]][[2]];*)
(*\[CapitalStigma]=TriNodes[[TriElements[[elem]][[ii]]]][[3]];*)
(*localK[[ii,jj]]=(1/2)(Subscript[\[Sigma], 1])^2*(\[CapitalPsi])^2*ddx\[Phi][\[CapitalPsi],\[CapitalStigma]][[jj]]+(Subscript[\[Sigma], 2])^2*(\[CapitalStigma])^2 ddy\[Phi][\[CapitalPsi],\[CapitalStigma]][[jj]]+Subscript[\[Sigma], 1] Subscript[\[Sigma], 2]\[Rho](\[CapitalPsi])(\[CapitalStigma])dxdy\[Phi][\[CapitalPsi],\[CapitalStigma]][[jj]]+r*\[CapitalPsi]*dx\[Phi][\[CapitalPsi],\[CapitalStigma]][[jj]]+r*\[CapitalStigma]*(dy\[Phi][\[CapitalPsi],\[CapitalStigma]][[jj]])-r*(\[Phi][\[CapitalPsi],\[CapitalStigma]][[jj]]);*)
(*jj++*)
(*];*)
(*ii++*)
(*];*)
(**)
(*(*Here we assemble the Global K & KM matrices ( KM=(\[CapitalDelta]tK+I))*)*)
(*\[CapitalDelta]t=.5;*)
(*kk=1;*)
(*While[kk<=6,*)
(*ll=1;*)
(*While[ll<=6,*)
(*globalK[[TriElements[[elem,kk]],TriElements[[elem,ll]]]]+=localK[[kk,ll]];*)
(*globalKM[[TriElements[[elem,kk]],TriElements[[elem,ll]]]]+=.5*(globalK[[TriElements[[elem,kk]],TriElements[[elem,ll]]]])+globalM[[TriElements[[elem,kk]],TriElements[[elem,ll]]]];*)
(*ll++*)
(*];*)
(*kk++*)
(*];*)
(*elem++*)
(*];*)
(*(*end of loop on elements*)*)


(* ::Input:: *)
(*(*boundary conditions: *)
(*We want to know what the fair price of an option is given that at expiration the value is one of the following{0 (if strike exceeds assets), ((asset1-strike)+(asset2-strike)), (asset1-strike+0 ) ,(asset2-strike+0) }.  *)
(* We will set up the boundary conditions accordingly)*)*)
(**)
(**)
(*strike=.4;*)
(*FS=ConstantArray[0,{Length[TriNodes],5}];*)
(**)
(*mm=1;*)
(*While[mm<=Length[TriNodes],*)
(*xx=TriNodes[[mm,2]];*)
(*yy=TriNodes[[mm,3]];*)
(*mx=Max[xx,yy];*)
(*If[(xx)>strike,$x=(xx-strike),$x=0];*)
(*If[(yy)>strike,$y=(yy-strike),$y=0];*)
(*FS[[mm,5]]=$x+$y;*)
(*mm++;*)
(*]*)


(* ::Input:: *)
(**)
(*(*FDM: In this case time stepping is backward from expiration to now*)*)
(*step=5;*)
(*nn=1;*)
(*While[nn<step,*)
(*FS[[All,step-nn]]=LinearSolve[globalKM,FS[[All,step-nn+1]]];*)
(*nn++*)
(*];*)
(**)
(**)


(* ::Input:: *)
(*(*LISTPLOT*)*)
(*yPlt={};*)
(*xPlt={};*)
(*ct3=1;*)
(*While[ct3<=Length[TriNodes],*)
(*AppendTo[xPlt,TriNodes[[ct3,2]]];*)
(*AppendTo[yPlt,TriNodes[[ct3,3]]];*)
(*ct3++;*)
(*]*)
(**)
(**)
(*FSPlt={};*)
(*cnt1=1;*)
(*While[cnt1<=5,*)
(*AppendTo[FSPlt,{FS[[All,step+1-cnt1]],xPlt,yPlt}];*)
(*cnt1++*)
(*];*)
(**)
(*FSPlt2=Transpose[FSPlt];*)
(**)
(*ListPointPlot3D[FSPlt2,AxesLabel->{"Spot","Time Steps","Option Value"}]*)
(*ListPlot3D[FSPlt2,AxesLabel->{"Spot","Time Steps","Option Value"}]*)



